Junos ospfv3 module dev
ansible-collections/junipernetworks.junos pull request #113
Opened 2020-10-27 10:11 UTC by rohitthakur2590

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2020-10-28 12:10 UTC, rohitthakur2590 commented
recheck

2020-10-28 15:43 UTC, GomathiselviS commented on plugins/module_utils/network/junos/facts/ospfv3/ospfv3.py
> +            # data = connection.get_configuration(filter=config_filter)
```suggestion
            # data = connection.get_configuration(filter=config_filter)
```

2020-10-28 15:43 UTC, GomathiselviS commented on plugins/module_utils/network/junos/facts/ospfv3/ospfv3.py
> +            # data = connection.get_configuration(filter=config_filter)
Please remove this commented line.

2020-10-28 15:46 UTC, GomathiselviS commented on plugins/modules/junos_ospfv3.py
> +- name: Gathere Junos OSPFv3 config
```suggestion
- name: Gather Junos OSPFv3 config
```

2020-10-28 15:53 UTC, GomathiselviS commented on tests/unit/modules/network/junos/test_junos_ospfv3.py
> +        self.assertEqual(sorted(result["commands"]), sorted(commands))
The 2 lines can be combined as 

`self.execute_module(changed=True, commands=commands)`

Same comment for the rest of the testcases as well. What do you think?

2020-10-28 15:54 UTC, GomathiselviS commented on tests/unit/modules/network/junos/test_junos_ospfv3.py
> +        self.execute_module(changed=True, commands=commands)
Please add testcases for the rest of the states as well. This will increase the test coverage percentage.

2020-10-28 15:56 UTC, GomathiselviS requested changes
Few nitpicks and testcases need to be added .

2020-10-29 12:04 UTC, justjais approved these changes

2020-10-29 13:49 UTC, merged