DNM Only wait for netconf when netconf
ansible-collections/junipernetworks.junos pull request #114
Opened 2020-10-28 19:51 UTC by cidrblock

##### SUMMARY
Testing a theory, thinking we should only wait for netconf if we enabled it

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
integration test, prepare
##### ADDITIONAL INFORMATION

2020-11-04 14:12 UTC, Qalthos approved these changes

2020-11-04 16:03 UTC, Qalthos commented on changelogs/fragments/int-test-fix.yaml
> +  - Integration test tag fix
I really don't like this fragment. If I found this in a changelog with no context, I would not feel any more enlightened than when I started, which seems to indicate that this fragment only exists to appease zuul and not to help anyone.

A more detailed change like "Changed integration tests to only wait for netconf availability when netconf is being tested" with a link back to the PR would be fine. A new changelog fragment type like `internal_changes` or `testing_changes` might be better. Skipping changelog fragment check on non-coding changes is my personal preference, but could be going too far.

2021-02-15 13:41 UTC, Qalthos requested changes

2021-02-15 13:41 UTC, Qalthos commented on changelogs/fragments/int-test-fix.yaml
> +bugfixes:
```suggestion
trivial:
```

2021-02-15 13:43 UTC, Qalthos approved these changes

2021-03-28 06:44 UTC, rohitthakur2590 commented
recheck

2021-03-28 14:33 UTC, merged