Junos[WIP]: deprecate router_id attribute
ansible-collections/junipernetworks.junos pull request #221
Opened 2021-08-24 10:17 UTC by rohitthakur2590

Signed-off-by: Rohit Thakur <rohitthakur2590@outlook.com>

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
 

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2021-08-25 13:20 UTC, Qalthos requested changes

2021-08-25 13:20 UTC, Qalthos commented on plugins/modules/junos_ospfv2.py
> +        - This attribute will be removed after 2023-08-01.
```suggestion
        - This attribute will be removed after 2024-01-01.
```

2021-08-29 14:46 UTC, rohitthakur2590 commented
recheck

2021-08-30 05:57 UTC, rohitthakur2590 commented
recheck

2021-08-30 13:17 UTC, Qalthos approved these changes

2021-09-23 14:24 UTC, merged