Remove pretty_print from call to ansible_utils to_text
ansible-collections/junipernetworks.junos pull request #226
Opened 2021-09-01 16:52 UTC by jake2184

##### SUMMARY
Fixes #225 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

plugins/module_utils/network/junos/junos.py

2022-05-16 05:59 UTC, rohitthakur2590 approved these changes

2022-05-16 05:59 UTC, rohitthakur2590 commented
recheck

2022-05-16 06:22 UTC, rohitthakur2590 requested changes

2022-05-16 06:22 UTC, rohitthakur2590 commented on changelogs/fix_tostring.yml
> +---
- Could you please have fragment with indicator as `bugfixes` and move this file to  `changelogs/fragments` directory, example: https://github.com/ansible-collections/junipernetworks.junos/pull/293/files

2022-09-16 12:51 UTC, avermeer-tc commented
This was fixed by https://github.com/ansible-collections/junipernetworks.junos/pull/306

2022-11-28 10:30 UTC, rohitthakur2590 commented
fixed by https://github.com/ansible-collections/junipernetworks.junos/pull/306

2022-11-28 10:30 UTC, closed without merging