Junos facts fix
ansible-collections/junipernetworks.junos pull request #256
Opened 2021-11-23 06:16 UTC by rohitthakur2590

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
 

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2021-11-23 06:38 UTC, NilashishC requested changes

2021-11-23 06:38 UTC, NilashishC commented on tests/integration/targets/junos_ospf_interfaces/tests/netconf/parsed.yaml
>                priority: 3
@rohitthakur2590 can we keep a test for this option to make sure that it works until it is removed?

2021-11-23 06:38 UTC, NilashishC commented on changelogs/fragments/junos_ospf_router_if_fix.yaml
> +  - Deprecated router_id from ospf-interfaces resource module.
We are deprecating it right now, but it does not have an alternative (i.e., junos_routing_options). I think we should deprecate it only when a correct option is available. To get past the reported traceback, maybe we just keep the if-condition.

2021-11-23 09:45 UTC, NilashishC approved these changes

2021-11-24 02:12 UTC, rohitthakur2590 commented
recheck

2021-11-24 06:43 UTC, rohitthakur2590 commented
recheck

2021-11-24 14:41 UTC, rohitthakur2590 commented
recheck

2021-11-25 04:22 UTC, rohitthakur2590 commented
recheck

2021-11-25 06:34 UTC, merged