Junos Hostname Resource Module Implemented
ansible-collections/junipernetworks.junos pull request #269
Opened 2022-01-22 18:48 UTC by rohitthakur2590

Signed-off-by: Rohit Thakur <rohitthakur2590@outlook.com>

##### SUMMARY

##### ISSUE TYPE

 
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2022-01-26 17:49 UTC, GomathiselviS commented on plugins/modules/junos_hostname.py
> +short_description: Manage SNMP server configuration on Junos devices.
```suggestion
short_description: Manage hostname configuration on Junos devices.
```

2022-01-26 17:50 UTC, GomathiselviS commented on plugins/modules/junos_hostname.py
> +description: This module manages SNMP server configuration on devices running Junos.
```suggestion
description: This module manages hostname configuration on devices running Junos.
```

2022-01-26 17:51 UTC, GomathiselviS commented on plugins/modules/junos_hostname.py
> +    - The state the configuration should be left in.
I think we should mention that the merged, replaced, and overridden states are going to behave the same for this module.

2022-01-26 17:52 UTC, GomathiselviS commented on tests/integration/targets/junos_hostname/tests/netconf/_populate_config.yaml
> +---
This file has to be removed.

2022-01-26 17:55 UTC, GomathiselviS requested changes
There are some minor changes to be done. Otherwise, the module looks good to be merged.

2022-01-31 05:39 UTC, KB-perByte commented on plugins/module_utils/network/junos/facts/hostname/hostname.py
> +        # Parse facts for BGP address-family global node
We can remove the comment  here

2022-01-31 05:39 UTC, KB-perByte commented on plugins/modules/junos_hostname.py
> +  sample: ['"<nc:host-name>78.46.194.186</nc:host-name></nc:system>"', 'command 2', 'command 3']
we may remove command 2 and 3 and keep the relevant one only

2022-01-31 06:06 UTC, KB-perByte approved these changes

2022-01-31 13:33 UTC, GomathiselviS approved these changes

2022-01-31 15:49 UTC, merged