JunOS Security Policies Global
ansible-collections/junipernetworks.junos pull request #284
Opened 2022-03-14 20:50 UTC by pranav-bhatt

This PR adds the security_policies_global module, which is responsible for managing the following security policy parameters:
- default_policy
- policy_rematch
- policy_stats
- pre_id_default_policy
- traceoptions
This module complements the JunOS Security Policies module, which allows defining of firewall and global security policies.

2022-03-16 03:18 UTC, pranav-bhatt commented
Recheck

2022-03-16 08:21 UTC, komaldesai13 commented
recheck

2022-03-17 08:10 UTC, pranav-bhatt commented
recheck

2022-03-17 14:35 UTC, pranav-bhatt commented
recheck

2022-03-21 09:04 UTC, komaldesai13 commented
depends on  https://github.com/ansible-network/windmill-config/pull/938#issue-1175047662

2022-03-21 09:04 UTC, komaldesai13 commented
recheck

2022-03-21 16:58 UTC, goneri commented
recheck

2022-03-24 09:30 UTC, rohitthakur2590 requested changes

2022-03-24 09:30 UTC, rohitthakur2590 commented on plugins/modules/junos_security_policies_global.py
> +    - overridden
We can mention that replaced and overridden will work in similar way

2022-03-24 09:30 UTC, rohitthakur2590 commented on plugins/modules/junos_security_policies_global.py
> +  returned: when state is I(merged), I(replaced), I(overridden), I(deleted) or I(purged)
we don't have purged for this

2022-03-24 09:30 UTC, rohitthakur2590 commented on plugins/modules/junos_security_policies_global.py
> +  returned: when state is I(merged), I(replaced), I(overridden), I(deleted) or I(purged)
puged is not supported

2022-03-24 09:30 UTC, rohitthakur2590 commented on plugins/modules/junos_security_policies_global.py
> +def main():
Please add functionality to check for empty config for opearation it is required.,
also test needs to be added for that

2022-03-25 14:43 UTC, goneri commented
recheck

2022-03-27 13:35 UTC, pranav-bhatt commented
recheck

2022-03-27 13:49 UTC, pranav-bhatt commented
recheck

2022-03-28 03:13 UTC, rohitthakur2590 commented
recheck

2022-03-28 05:03 UTC, rohitthakur2590 approved these changes

2022-03-28 05:04 UTC, merged