Resume provider support and Deprecate junos_scp and junos_package modules
ansible-collections/junipernetworks.junos pull request #350
Opened 2022-12-09 14:42 UTC by rohitthakur2590

Signed-off-by: rohitthakur2590 <rohitthakur2590@outlook.com>

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2022-12-09 14:54 UTC, Qalthos requested changes
Instead reintroducing provider everywhere, Just add the provider dictionary (deprecated) to those two modules, and also modify https://github.com/ansible-collections/junipernetworks.junos/blob/main/plugins/module_utils/network/junos/junos.py#L103 to request the params from the connection plugin in addition to provider.

2022-12-09 14:54 UTC, Qalthos commented on plugins/doc_fragments/junos.py
> +    DOCUMENTATION = r"""options:
We absolutely do not want to return this to every module. Just package and scp should be fine.

2022-12-09 14:54 UTC, Qalthos commented on plugins/modules/junos_package.py
> +short_description: (deprecated, removed after 2025-12-01) Installs packages on remote devices running Junos
Are we really deprecating this one though? It should work without provider even if it doesn't technically use the connection plugin
```suggestion
short_description: (deprecated, removed after 2025-01-01) Installs packages on remote devices running Junos
```

2022-12-09 14:54 UTC, Qalthos commented on plugins/modules/junos_scp.py
> +short_description: (deprecated, removed after 2025-12-01) Transfer files from or to remote devices running Junos
```suggestion
short_description: (deprecated, removed after 2025-01-01) Transfer files from or to remote devices running Junos
```

2022-12-09 14:54 UTC, Qalthos commented on meta/runtime.yml
> +        removal_date: "2025-12-01"
```suggestion
        removal_date: "2025-01-01"
```

2022-12-09 14:54 UTC, Qalthos commented on meta/runtime.yml
> +        removal_date: "2025-12-01"
```suggestion
        removal_date: "2025-01-01"
```

2023-02-28 07:00 UTC, ashwini-mhatre approved these changes

2023-02-28 07:51 UTC, merged