Fix implementation of enable attribute
ansible-collections/junipernetworks.junos pull request #401
Opened 2023-04-04 10:32 UTC by rohitthakur2590

##### SUMMARY

Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1796

##### ISSUE TYPE

- Bugfix Pull Request
 

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2023-04-04 10:46 UTC, KB-perByte approved these changes

2023-04-04 16:05 UTC, rohitthakur2590 commented
recheck

2023-04-05 10:11 UTC, rohitthakur2590 commented
recheck

2023-04-05 13:34 UTC, Qalthos requested changes

2023-04-05 13:34 UTC, Qalthos commented on changelogs/fragments/fix_enabling.yaml
> +  - fix the implementation of disabling interface.
```suggestion
  - junos_interfaces - fix the behavior of ``enabled`` option. (https://github.com/ansible-collections/junipernetworks.junos/pull/401)
```

2023-04-10 10:44 UTC, rohitthakur2590 commented
recheck

2023-04-17 09:14 UTC, rohitthakur2590 commented
recheck

2023-04-20 14:06 UTC, komaldesai13 commented
recheck

2023-04-21 05:55 UTC, komaldesai13 commented
reacheck

2023-04-21 05:56 UTC, komaldesai13 commented
recheck

2023-04-21 07:04 UTC, komaldesai13 commented
recheck

2023-04-24 14:27 UTC, komaldesai13 commented
recheck

2023-04-27 08:38 UTC, rohitthakur2590 commented
recheck

2023-04-27 11:15 UTC, rohitthakur2590 commented
recheck

2023-04-27 14:00 UTC, merged