Improve docs of static routes
ansible-collections/junipernetworks.junos pull request #402
Opened 2023-04-04 11:28 UTC by ashwini-mhatre

##### SUMMARY

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2023-04-05 04:39 UTC, rohitthakur2590 requested changes

2023-04-05 04:39 UTC, rohitthakur2590 commented on plugins/modules/junos_static_routes.py
> +# Task Output
```suggestion
# Task Output:
--------------
```

2023-04-05 04:39 UTC, rohitthakur2590 commented on plugins/modules/junos_static_routes.py
> +# Task Output
```suggestion
# Task Output:
--------------
```

2023-04-05 04:39 UTC, rohitthakur2590 commented on plugins/modules/junos_static_routes.py
> +# Task Output
```suggestion
# Task Output:
--------------
```

2023-04-05 04:39 UTC, rohitthakur2590 commented on plugins/modules/junos_static_routes.py
> +# Task Output
```suggestion
# Task Output:
--------------
```

2023-04-05 04:46 UTC, rohitthakur2590 requested changes

2023-04-05 04:46 UTC, rohitthakur2590 commented on plugins/modules/junos_static_routes.py
> +# Task Output
Lets follow the same format for before state and After state as we are doing for all the documentations now:
# Before state:
# -----------------

2023-04-05 04:46 UTC, rohitthakur2590 commented on plugins/modules/junos_static_routes.py
>  - name: Override provided configuration with device configuration (default operation
Override running configuration with provided configuration

2023-04-05 04:46 UTC, rohitthakur2590 commented on plugins/modules/junos_static_routes.py
> +
Need to have examples for gathered, parsed and rendered .

2023-04-05 13:32 UTC, Qalthos requested changes

2023-04-05 13:32 UTC, Qalthos commented on changelogs/fragments/fix_docs_static_route.yaml
> +  - Fix docs of static routes.
```suggestion
  - junos_static_routes - add task output to module documentation examples. (https://github.com/ansible-collections/junipernetworks.junos/pull/402)
```

2023-04-27 10:58 UTC, rohitthakur2590 commented
recheck

2023-04-27 11:04 UTC, rohitthakur2590 commented on plugins/modules/junos_static_routes.py
>  RETURN = """
could you also include documentation as below:  
rendered:
  description: The provided configuration in the task rendered in device-native format (offline).
  returned: when I(state) is C(rendered)
  type: list
  sample:
    - <nc:protocols xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
gathered:
  description: Facts about the network resource gathered from the remote device as structured data.
  returned: when I(state) is C(gathered)
  type: list
  sample: >
    This output will always be in the same format as the
    module argspec.
parsed:
  description: The device native config provided in I(running_config) option parsed into structured data as per module argspec.
  returned: when I(state) is C(parsed)
  type: list
  sample: >
    This output will always be in the same format as the
    module argspec.

2023-04-28 05:48 UTC, merged