Prepare Major release 7.0.0
ansible-collections/junipernetworks.junos pull request #508
Opened 2024-03-27 14:40 UTC by rohitthakur2590

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2024-03-27 15:29 UTC, NilashishC commented on CHANGELOG.rst
> -- junos_logging - Manage logging on network devices
Should we revert this?

2024-03-27 15:29 UTC, NilashishC commented on changelogs/changelog.yaml
> -      - description: Manage logging on network devices
Same as above.

2024-03-27 15:29 UTC, NilashishC requested changes
Can you also remove meta/runtime.yml entries?

2024-03-28 03:06 UTC, rohitthakur2590 commented on CHANGELOG.rst
> -- junos_logging - Manage logging on network devices
yes I'll update with the reverts.

2024-03-28 09:14 UTC, rohitthakur2590 commented
recheck

2024-03-28 10:49 UTC, merged